name: Process SQM/TESS files with DSN_V01.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libgtk-3-dev
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files and process with Python
      run: |
          echo "Listing files in the current directory:"
          FILES=$(ls -1 DSNdata/NEW)
          if [ -z "$FILES" ]; then
            echo "Error: No files found." >&2
            exit 1
          fi

          echo "Running Python script on each file:"
          for file in $FILES; do
            echo "Processing $file"
            python3 DSN_V01.py "$file"
          done
