name: Process DSN data
# Trigger the workflow on a schedule (in production mode)
on:
 workflow_dispatch:
#  schedule:
#    - cron: '0 17 * * 0-7'  # Runs every day at 17:00 UTC
#  push:
#    branches:
#      - main  # Trigger on push to the 'main' branch
#  pull_request:
#    branches:
#      - main

jobs:
  process_and_upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Up Environment
      - name: Set Up Dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y curl jq

      # Step 3: Install Influx CLI
      - name: Install Influx CLI
        run: |
          echo "Installing InfluxDB CLI..."
         curl -sL https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.5-linux-amd64.tar.gz -o influxdb2-client.tar.gz
          tar -xzf influxdb2-client.tar.gz
          sudo mv influx /usr/local/bin/
          influx version

      # Step 4: Check for CSV Files and Upload to InfluxDB Cloud
      - name: Upload CSV Files to InfluxDB Cloud
        env:
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        run: |
          CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')
          ORIG_FILES=$(ls -1 $(pwd)/DSNdata/NEW)
          if [ -z "$ORIG_FILES" ]; then
            echo "Error: $ORIG_FILES not found." >&2
            echo $CURRENT_DATE "No data files to box." >> DSNdata/RUN_LOG
            exit 1
          fi
          IN_FILES=$(ls -1 DSNdata/INFLUX/*.csv 2>/dev/null || true)
          if [ -z "$IN_FILES" ]; then
            echo "Error: $IN_FILES not found." >&2
            exit 1
          fi
          influx config rm default || true
          echo "Run influx write on $IN_FILES"
          for infile in $IN_FILES; do
            echo "Uploading $infile to InfluxDB Cloud..."
            influx write \
              --url https://us-east-1-1.aws.cloud2.influxdata.com \
              --org DSN \
              --bucket DSNdata \
              --token $INFLUX_TOKEN \
              --file "$infile" \
              --format csv \
             --debug

          if [ $? -ne 0 ]; then
            echo "Error: Failed to upload $infile to InfluxDB Cloud." >&2
            exit 1
          fi
          done
          echo $CURRENT_DATE $ORIG_FILES" boxed." >> DSNdata/RUN_LOG

      - name: Commit files # commit data folders
        env:
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        run: |
          git config --local user.email "soazcomms@darksky.org"
          git config --local user.name "GitHub Action test"
          if [[ -n $(git status --porcelain) ]]; then
            git add ./DSNdata ./DSNdata/NEW ./DSNdata/INFLUX ./DSNdata/BOX 
            git commit -m "Add changes"
          else
            echo "No changes to commit"
          fi

      # Step 5: 
      - name: Commit files # commit data folders
        env:
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        run: |
          git config --local user.email "soazcomms@darksky.org"
          git config --local user.name "GitHub Action test"
          if [[ -n $(git status --porcelain) ]]; then
            git add ./DSNdata ./DSNdata/NEW ./DSNdata/INFLUX ./DSNdata/BOX 
            git commit -m "Add changes"
          else
            echo "No changes to commit"
          fi

      - name: Push changes # push modified folders to repo
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger GitToB%ox Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-git-to-box

