name: Install and Run Influx CLI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-and-write:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          echo "Installing Homebrew..."
          sudo apt-get update
          sudo apt-get install -y build-essential curl dos2unix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" >/dev/null 2>&1
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.profile
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.bashrc
          source ~/.profile
          brew --version

      - name: Install Influx CLI
        run: |
          echo "Installing Influx CLI..."
          source ~/.profile
          brew update
          brew install influxdb-cli
          influx version

      - name: Set Environment Variables
        run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8

      - name: Write minimal Test Data to InfluxDB
        env:
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        run: |
          cp DSNdata/INFLUX/test.csv /tmp/test.csv
          source ~/.profile
          influx write \
            --url https://us-east-1-1.aws.cloud2.influxdata.com \
            --org DSN \
            --bucket TEST \
            --token $INFLUX_TOKEN \
            --file /tmp/test.csv \
            --format csv \
            --skipRowOnError \
            --errors-file /tmp/ERRORS
          echo "Original Test Error File Contents:"
          cat /tmp/ERRORS || true
