- name: Debug File Inspection
  run: |
    echo "Inspecting file content and line endings..."
    file DSNdata/INFLUX/DSN-MtLemmon_23.csv
    cat -v DSNdata/INFLUX/DSN-MtLemmon_23.csv | head -n 10 || true
    hexdump -C DSNdata/INFLUX/DSN-MtLemmon_23.csv | head -n 10 || true

- name: Write data to InfluxDB
  env:
    INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
  run: |
    cp DSNdata/INFLUX/DSN-MtLemmon_23.csv /tmp/DSN-MtLemmon_23.csv
    influx write \
      --url https://us-east-1-1.aws.cloud2.influxdata.com \
      --org DSN \
      --bucket DSNdata \
      --token $INFLUX_TOKEN \
      --file /tmp/DSN-MtLemmon_23.csv \
      --format csv \
      --skipRowOnError \
      --errors-file /tmp/ERRORS
    echo "Error File Contents:"
    cat /tmp/ERRORS || true