name: Minimal InfluxDB Write

on:
  workflow_dispatch:

jobs:
  minimal-influx-write:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Influx CLI Manually
        run: |
          echo "Downloading and installing Influx CLI..."
          curl -sL https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.5-linux-amd64.tar.gz -o influxdb2-client.tar.gz
          tar xvzf influxdb2-client.tar.gz
          echo "Listing contents of current directory after extraction:"
          ls -l
          echo "Checking if 'influx' binary exists directly after extraction:"
          if [ -f influx ]; then
            sudo mv influx /usr/local/bin/
          else
            echo "'influx' binary not found directly. Checking for extracted directory..."
            EXTRACTED_DIR=$(find . -type d -name 'influxdb2-client-*')
            if [ -d "$EXTRACTED_DIR" ]; then
              echo "Found extracted directory: $EXTRACTED_DIR"
              sudo mv "$EXTRACTED_DIR/influx" /usr/local/bin/
            else
              echo "No valid directory or binary found. Exiting with error."
              exit 1
            fi
          fi
          echo "Influx CLI installed to /usr/local/bin"
          which influx
          influx version

      - name: Set Locale and Environment
        run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          export INFLUXDB_DEBUG=true
          env

      - name: Write Minimal Data to InfluxDB
        env:
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        run: |
          influx write \
            --url https://us-east-1-1.aws.cloud2.influxdata.com \
            --org DSN \
            --bucket TEST \
            --token $INFLUX_TOKEN \
            --file DSNdata/INFLUX/test.csv \
            --format csv \
            --debug \
            --errors-file /tmp/errors.log
          echo "======================"
          echo "Error File Contents:"
          echo "======================"
          cat /tmp/errors.log || true
