name: Minimal InfluxDB Write

on:
  workflow_dispatch:

jobs:
  minimal-influx-write:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Influx CLI
        run: |
          echo "Downloading and installing Influx CLI..."
          curl -sL https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.5-linux-amd64.tar.gz -o influxdb2-client.tar.gz
          tar xvzf influxdb2-client.tar.gz
          echo "Listing contents of current directory:"
          ls -l
          echo "Finding the extracted directory..."
          EXTRACTED_DIR=$(find . -type d -name 'influxdb2-client-*')
          echo "Extracted directory: $EXTRACTED_DIR"
          sudo mv "$EXTRACTED_DIR/influx" /usr/local/bin/
          echo "Influx CLI installed to /usr/local/bin"
          which influx
          influx version

      - name: Write Minimal Data to InfluxDB
        env:
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        run: |
          echo "timestamp,location,value" > test.csv
          echo "2023-01-17T10:00:00Z,office,22.5" >> test.csv
          influx write \
            --url https://us-east-1-1.aws.cloud2.influxdata.com \
            --org DSN \
            --bucket TEST \
            --token $INFLUX_TOKEN \
            --file test.csv \
            --format csv \
            --skipRowOnError \
            --errors-file errors.log
          echo "Error File Contents:"
          cat errors.log || true
