name: Upload Local DSNdata/NEW into soazcomms.github.io

on:
  # Trigger manually via the "Run workflow" button
  # OR you can set "schedule:" here if you want it timed
  workflow_dispatch:

env:
  GIT_PATH: "soazcomms/soazcomms.github.io/"

jobs:
  upload-local-dsndata:
    # Run on your self-hosted runner so it can see local folders
    runs-on: self-hosted

    steps:
      # STEP 1: Make a temp directory for staging files
      - name: Prepare workspace
        run: |
          mkdir -p temp_dsn
          ls -al

      # STEP 2: Copy files from your *local* DSNdata/NEW 
      #         into the temp staging directory.
      #    Replace /absolute/path/to/DSNdata/NEW with the
      #    actual path on your local machine.
      - name: Copy DSNdata/NEW from local
        run: |
          cp -R /Users/Bun/Downloads/soazcomms.github.io/DSNdata/NEW/* temp_dsn/

      # STEP 3: Check out the soazcomms.github.io repo *into* a folder named 'soazcomms'
      #         so we can modify it.
      - name: Check out soazcomms.github.io
        uses: actions/checkout@v3
        with:
          repository: soazcomms/soazcomms.github.io
          # This uses the default token to push commits back
          token: ${{ secrets.GITHUB_TOKEN }}
          path: soazcomms

      # STEP 4: Copy staged files from temp_dsn into soazcomms/DSNdata/NEW
      - name: Copy files into soazcomms.github.io
        run: |
          cp -R temp_dsn/* $GIT_PATH"DSNdata/NEW/"
          ls -al $GIT_PATH"DSNdata/NEW"

      # STEP 5: Commit and push changes
      - name: Commit and push
        run: |
          cd $GIT_PATH
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage changes in DSNdata/NEW
          git add $GIT_PATH"DSNdata/NEW"

          # Only commit if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update DSNdata/NEW from local mac"
            git push
          else
            echo "No changes to commit."
