name: Load InfluxDB Data

on:
  push:
    branches:
      - main

jobs:
  load-influxdb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and configure InfluxDB
        uses: influxdata/influxdb-action@main
        with:
          influxdb_version: '2.0.7'
          influxdb_start: true
          influxdb_org: 'DSN'
          influxdb_user: 'soazcomms'
          influxdb_password: ${{ secrets.SOAZCOMMS_GITHUB_IO_PASSWORD }}
          influxdb_bucket: 'DSNdata'

      - name: Write data to InfluxDB
        run: |
          echo "Writing data to InfluxDB bucket..."
          INFLUX_TOKEN=$(influx auth list --json | jq -r '.[0].token')
          influx write \
            --host http://localhost:8086 \
            --org DSN \
            --bucket DSNdata \
            --token $INFLUX_TOKEN \
            --file DSNdata/PROCESSED/DSN-MtLemmon_23.csv \
            --format csv