#  schedule:
#    - cron: '0 17 * * 0-7'  # Runs every day at 17:00 UTC
#  push:
#    branches:
#      - main  # Trigger on push to the 'main' branch
#  pull_request:
#    branches:
#      - main
#  schedule:
#    - cron: '0 17 * * 0-7'  # Runs every day at 17:00 UTC
#  push:
#    branches:
#      - main  # Trigger on push to the 'main' branch
#  pull_request:
#    branches:
#      - main
name: Upload Local DSNdata/NEW into soazcomms.github.io

on:
  # Trigger manually via the "Run workflow" button
  # OR you can set "schedule:" here if you want it timed
  workflow_dispatch:
#  schedule:
#    - cron: '0 17 * * 0-7'  # Runs every day at 17:00 UTC
#  push:
#    branches:
#      - main  # Trigger on push to the 'main' branch
#  pull_request:
#    branches:
#      - main

jobs:
  upload-local-dsndata:
    # Run on your self-hosted runner so it can see local folders
    runs-on: self-hosted

    steps:
      # STEP 1: Make a temp directory for staging files
      - name: Prepare workspace
        run: |
          mkdir -p temp_dsn
          ls -al

      # STEP 2: Copy files from your *local* DSNdata/NEW 
      #         into the temp staging directory.
      #    Replace /absolute/path/to/DSNdata/NEW with the
      #    actual path on your local machine.
      - name: Copy DSNdata/NEW from local
        run: |
          cp -R /absolute/path/to/DSNdata/NEW/* temp_dsn/

      # STEP 3: Check out the repo *into* a folder named 'soazcomms'
      #         so we can modify it.
      - name: Check out soazcomms.github.io
        uses: actions/checkout@v3
        with:
          repository: soazcomms/soazcomms.github.io
          # This uses the default token to push commits back
          token: ${{ secrets.GITHUB_TOKEN }}
          path: soazcomms

      # STEP 4: Copy staged files from temp_dsn into soazcomms/DSNdata/NEW
      - name: Copy files into soazcomms.github.io
        run: |
          cp -R temp_dsn/* soazcomms/DSNdata/NEW/
          ls -al soazcomms/DSNdata/NEW

      # STEP 5: Commit and push changes
      - name: Commit and push
        run: |
          cd soazcomms
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage changes in DSNdata/NEW
          git add DSNdata/NEW

          # Only commit if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update DSNdata/NEW from local machine"
            git push
          else
            echo "No changes to commit."
