name: Process SQM/TESS data
# Trigger the workflow on a schedule (in production mode)
on:
 workflow_dispatch:
#  schedule:
#    - cron: '0 17 * * 0-7'  # Runs every day at 17:00 UTC
#  push:
#    branches:
#      - main  # Trigger on push to the 'main' branch
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libgtk-3-dev libc-bin curl
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process SQM/TESS files
      run: |
        FILES=$(ls -1 DSNdata/NEW)
        if [ -z "$FILES" ]; then
          echo "Error: No files found." >&2
          exit 1
        fi
        for file in $FILES; do
          new_file="DSNdata/NEW/$file"
          echo "Process $new_file"
          python3 DSN_V03.py $new_file
        done

    - name: Install Influx CLI
      run: |
        echo "Downloading and installing Influx CLI..."
        curl -sL https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.5-linux-amd64.tar.gz -o influxdb2-client.tar.gz
        tar xvzf influxdb2-client.tar.gz
        echo "Checking if 'influx' binary exists directly after extraction:"
        if [ -f influx ]; then
          sudo mv influx /usr/local/bin/
        else
          echo "'influx' binary not found directly. Checking for extracted directory..."
          EXTRACTED_DIR=$(find . -type d -name 'influxdb2-client-*')
          if [ -d "$EXTRACTED_DIR" ]; then
            echo "Found extracted directory: $EXTRACTED_DIR"
            sudo mv "$EXTRACTED_DIR/influx" /usr/local/bin/
          else
            echo "No valid directory or binary found. Exiting with error."
            exit 1
          fi
        fi
        echo "Influx CLI installed to /usr/local/bin"
        
    - name: Start InfluxDB
      run: |
        echo "Starting InfluxDB..."
        docker run -d \
          --name influxdb \
          -p 8086:8086 \
          -e INFLUXDB_ADMIN_USER=admin \
          -e INFLUXDB_ADMIN_PASSWORD=StrongP@ssw0rd \
          -e INFLUXDB_DB=dsn \
          influxdb:2.0
        echo "Waiting for InfluxDB to be ready..."
        until curl -s http://localhost:8086/ping; do sleep 1; done
  
    - name: Set up InfluxDB
      env:
        INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
      run: |
        echo "Setting up InfluxDB..."
        docker exec influxdb influx setup --skip-verify --bucket TEST --org DSN --username admin --password StrongP@ssw0rd --token $INFLUX_TOKEN --force

    - name: Run InfluxDB Write in Docker
      env:
        INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
      run: |
        CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')
        ORIG_FILES=$(ls -1 $(pwd)/DSNdata/NEW)
        if [ -z "$ORIG_FILES" ]; then
          echo "Error: $ORIG_FILES not found." >&2
          echo $CURRENT_DATE "No data files to box." >> DSNdata/RUN_LOG
          exit 1
        fi
        IN_FILES=$(ls -1 $(pwd)/DSNdata/INFLUX)
        if [ -z "$IN_FILES" ]; then
          echo "Error: $IN_FILES not found." >&2
          exit 1
        fi
        echo "Run influx write on " $IN_FILES
        for infile in $IN_FILES; do
          docker cp ./DSNdata/INFLUX/$infile influxdb:/tmp/intake.csv
          docker exec influxdb influx bucket list
          docker exec influxdb influx write \
            --host http://localhost:8086 \
            --org DSN \
            --bucket DSNdata \
            --token $INFLUX_TOKEN \
            --file /tmp/intake.csv \
            --format csv
        done
        echo $CURRENT_DATE $ORIG_FILES" boxed." >> DSNdata/RUN_LOG
    - name: Commit files # commit data folders
      env:
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
      run: |
        git config --local user.email "soazcomms@darksky.org"
        git config --local user.name "GitHub Action test"
        if [[ -n $(git status --porcelain) ]]; then
          git add ./DSNdata ./DSNdata/NEW ./DSNdata/INFLUX ./DSNdata/BOX 
          git commit -m "Add changes"
        else
          echo "No changes to commit"
        fi

    - name: Push changes # push modified folders to repo
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger GitToBox Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: trigger-git-to-box
