name: Process SQM/TESS files with DSN_V01.py

on:
  push:
    branches:
      - main

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files and process with Python
        run: |
          echo "Listing files in the current directory:"
          FILES=$(ls -1)
          if [ -z "$FILES" ]; then
            echo "Error: No files found." >&2
            exit 1
          fi

          echo "Running Python script on each file:"
          for file in $FILES; do
            echo "Processing $file"
            python3 DSN_V01.py "$file"
          done
