name: Process SQM/TESS files with DSN_V02.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libgtk-3-dev
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files and process with Python
      run: |
          echo "Listing files in DSNdata/NEW"
          FILES=$(ls -1 DSNdata/NEW)
          if [ -z "$FILES" ]; then
            echo "Error: No files found." >&2
            exit 1
          fi

          echo "Running Python script on each file:"
          for file in $FILES; do
            echo "Processing $file"
            python3 DSN_V02.py "DSNdata/NEW/$file"
          done
    - name: Commit files # commit the PROCESSED folder
      run: |
    	 git config --local soazcomms@darksky.org "test@github.com"
    	 git config --local user.name "GitHub Action test"
    	 git add ./DSNdata/PROCESSED
	 git commit -m "Add changes"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
