name: Upload to Box

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Box CLI
      - name: Install Box CLI
        run: |
          echo "Installing Box CLI..."
          sudo apt-get update
          sudo apt-get install -y box

      # Step 3: Write `config.json` File
      - name: Write `config.json` File
        env:
          BOX_CONFIG: ${{ secrets.BOX_CONFIG }}
        run: |
          echo "$BOX_CONFIG" > box_config.json

      # Step 4: Authenticate Box CLI
      - name: Authenticate Box CLI
        run: |
          box configure:environments:add box_config.json
          box configure:environments:set-current "github-box"

      # Step 5: Upload All Files in a Folder to Box
      - name: Upload All Files to Box
        env:
          BOX_FOLDER_ID: "304428997491"  # Box folder DSNdata/ARCHIVE ID
        run: |
          echo "Upload DSNdata/INFLUX files to Box"
          for file in DSNdata/INFLUX/*; do
            if [ -f "$file" ]; then
              echo "Upload $file to Box..."
              box files:upload "$file" "$BOX_FOLDER_ID"
            else
              echo "No files found in DSNdata/INFLUX to upload."
            fi
          done

      # Step 6: Clean Up `config.json`
      - name: Clean Up
        run: |
          rm -f box_config.json
