name: Upload to Box

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js LTS version

      # Step 3: Install Box CLI via npm
      - name: Install Box CLI
        run: |
          echo "Installing Box CLI via npm..."
          npm install -g @box/cli
          box --version

      # Step 4: Write `config.json` File
      - name: Write `config.json` File
        env:
          BOX_CONFIG_FILE: ${{ secrets.BOX_CONFIG }}
        run: |
          echo "$BOX_CONFIG_FILE" > box_config.json

      # Step 5: Authenticate Box CLI
      - name: Authenticate Box CLI
        run: |
          box configure:environments:add "github-box" --file=box_config.json
          box configure:auth --environment="github-box"

      # Step 6: Upload All Files in a Folder to Box
      - name: Upload All Files to Box
        env:
          BOX_FOLDER_ID: "304428997491"  # Box folder DSNdata/ARCHIVE ID
        run: |
          echo "Upload files from DSNdata/INFLUX to Box DSNdata/ARCHIVE"
          for file in DSNdata/INFLUX/*; do
            if [ -f "$file" ]; then
              echo "Uploading $file to Box..."
              box files:upload "$file" "$BOX_FOLDER_ID"
            else
              echo "No files found in DSNdata/INFLUX to upload."
            fi
          done

      # Step 7: Clean Up `config.json`
      - name: Clean Up
        run: |
          rm -f box_config.json
